CMS ARS 3.1 AWS RDS Low Overlay
CMSgov/cms-ars-3.1-low-aws-rds-microsoft-sql-server-2017-cis-overlay pull request #1
Opened 2022-05-06 13:36 UTC by karikarshivani

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

2022-05-06 13:37 UTC, karikarshivani commented on inspec.yml
> +  url: https://github.com/mitre/aws-rds-microsoft-sql-server-2017-cis-baseline/archive/v1.2.0.tar.gz
I'll update the branch name in the `depends.url` when the PR for the baseline has been approved and merged. Thanks!

2022-06-09 20:14 UTC, ejaronne requested changes
microsoft-sql-server-2017-cis-1.2 relates to SI-10 (only for Mod/High) and SC-32 (non-mandatory). In planning in CFACTS, CMS ARS 3.1 non-mandatory controls are optional for ISSOs to adopt, and therefore may be something they still wish to include in their application's control set. Therefore, we don't exclude (make not applicable) a requirement based on non-mandatory NIST controls.

2022-06-09 22:16 UTC, ejaronne commented
update depends reference to main.tar.gz (not 1.2.0)
update README exec instructions to use main.tar.gz (not master)
update README "full heimdall server" url to point to heimdall2 repo not old heimdall

2022-06-10 02:12 UTC, ejaronne approved these changes
typo corrections added to README and inspec.yml

2022-06-10 02:15 UTC, ejaronne approved these changes

2022-06-10 18:12 UTC, karikarshivani commented on inspec.yml
> +  url: https://github.com/mitre/aws-rds-microsoft-sql-server-2017-cis-baseline/archive/v1.2.0.tar.gz
Branch name updated

2022-06-10 18:13 UTC, karikarshivani commented
> microsoft-sql-server-2017-cis-1.2 relates to SI-10 (only for Mod/High) and SC-32 (non-mandatory). In planning in CFACTS, CMS ARS 3.1 non-mandatory controls are optional for ISSOs to adopt, and therefore may be something they still wish to include in their application's control set. Therefore, we don't exclude (make not applicable) a requirement based on non-mandatory NIST controls.

Thanks for pointing it out! Removed the caveat for 1.2
PR ready to be merged!

2022-06-11 15:15 UTC, merged